### ISSUE TITLE
Генерация стиха по первой строчке от пользователя 

### ISSUE THREAD

**Issue by Lisennk** [IlyaGusev/PoetryCorpus#23]

**Comment by Lisennk** [comment]
А в каких случаях отказ?

**Comment by IlyaGusev** [comment]
Если нет подходящих слов.


06 марта 2017 г. 22:02 пользователь "Taras Lisennk" <
notifications@github.com> написал:

А в каких случаях отказ?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/IlyaGusev/PoetryCorpus/issues/23#issuecomment-284497223>,
or mute the thread

**Comment by IlyaGusev** [comment]
Там пока разметки пересчитываются, через час где-то сможешь посмотреть.

06 марта 2017 г. 22:04 пользователь "Allen" <phoenixilya@gmail.com> написал:

**Comment by Lisennk** [comment]
тогда я так понимаю, это редко бывает, что нет слов, база ведь большая. 

Ещё вот такая идея: если нет слова, то просто рандомное брать, для пользователя будет хоть что-то.

**Comment by IlyaGusev** [comment]
На текущей модели - часто, потому что она на маленьком подкорпусе для
скорости построена. Можно, но я ставил задачу именно с жёсткими
ограничениями. Можно галочку сделать, которая это регулирует.


06 марта 2017 г. 22:08 пользователь "Taras Lisennk" <
notifications@github.com> написал:

тогда я так понимаю, это редко бывает, что нет слов, база ведь большая.

Ещё вот такая идея: если нет слова, то просто рандомное брать, для
пользователя будет хоть что-то.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/IlyaGusev/PoetryCorpus/issues/23#issuecomment-284498864>,
or mute the thread

**Comment by Lisennk** [comment]
1. Сделаешь? 
2. Т.е. если взять больше подкорпус то будет больше время ожидания для пользователя?

**Comment by IlyaGusev** [comment]
Да, да. Но я стараюсь ускорить.

06 марта 2017 г. 22:14 пользователь "Taras Lisennk" <
notifications@github.com> написал:


   1. Сделаешь?
   2. Т.е. если взять больше подкорпус то будет больше время ожидания для
   пользователя?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/IlyaGusev/PoetryCorpus/issues/23#issuecomment-284500590>,
or mute the thread

**Comment by Lisennk** [comment]
Я просто хочу использовать это в одном своем проекте и там скорость важна, т.е. лучше не такой хорошей стих получить, но чтобы получить. Может какое-то кеширование можно добавить?

**Comment by IlyaGusev** [comment]
Это можно регулировать. Кэшировать там нечего.

06 марта 2017 г. 22:17 пользователь "Taras Lisennk" <
notifications@github.com> написал:

Я просто хочу использовать это в одном своем проекте и там скорость важна,
т.е. лучше не такой хорошей стих получить, но чтобы получить. Может
какое-то кеширование можно добавить?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/IlyaGusev/PoetryCorpus/issues/23#issuecomment-284501717>,
or mute the thread

**Comment by IlyaGusev** [comment]
Вообще я ещё полноценно не опоптимизировал, может и норм будет.

06 марта 2017 г. 22:20 пользователь "Allen" <phoenixilya@gmail.com> написал:

**Comment by Lisennk** [comment]
попробуешь оптимизировать? Кстати, сайт не работает

**Comment by IlyaGusev** [comment]
Да. Я же написал, корпус переразмечается.

06 марта 2017 г. 22:28 пользователь "Taras Lisennk" <
notifications@github.com> написал:

попробуешь оптимизировать? Кстати, сайт не работает

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/IlyaGusev/PoetryCorpus/issues/23#issuecomment-284504838>,
or mute the thread

**Comment by Lisennk** [comment]
А когда оптимизации ждать?

**Comment by IlyaGusev** [comment]
Примерно в конце недели.

06 марта 2017 г. 22:30 пользователь "Taras Lisennk" <
notifications@github.com> написал:

А когда оптимизации ждать?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/IlyaGusev/PoetryCorpus/issues/23#issuecomment-284505295>,
or mute the thread
